### ISSUE TITLE
Transportation Service

### ISSUE THREAD

**Issue by qjhart** [CSTARS/ahb-decision-support-sdk#1]
The current transportation stub passes destination as a [longituge,latitude] pair, and an array of sources as [[lon,lat],[lon,lat].  The response is geojson, as an (array?) for linestring geojson features including a distance as a property.  

I suggest the transportation function passes in a src geojson object, a destination geojson object, and a set of json options.  The results is a geojson featureCollection of the transportation network used, including the paths traveled on it, and a separate geojson featureCollection of the paths traveled.  This could also be a single FeatureCollection with feature types differentiated by there use.  Features should include an identifier.

A source and destination can also be a geometry collection, in which case identifiers are calculated for the points and destinations.  The IDs are MD5 calculations of the geometries.  Features without id's are considered to be simple geometries, and their ID's calculated the same way.

The service takes the centroid of all sources and destinations, so the client should think about doing that before sending.

Input:

``` json
{
"destination": {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [-123,46.72]
            },
            "properties": {
                "id":"centraila",
                "name": "Centrailia"
            }
        }]
},
"source": {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [-122.5,46.5]
            },
            "properties": {
                "id":"farm1",
                "name": "Farm1"
            }
        }]
},
"options": {
   "costs":{
      "diesel_per_gal": 2.14,
      "labor_per_hour":32.16
   }
}
```

For the output, the id's are calculated in a similar manner, the MD5 of the geometries are used for the id's of the paths.  The source and destination match the input data.  Similarly, the id's for the features in the network are MD5's of the geometry of the features as well.

Output: 

``` json
{"paths":{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "LineString",
                "coordinates": [[-122,46.5],[-123,46.72]]
            },
            "properties": {
                "id":"farm1-centrailia",
                "source":"farm1",
                "destination": "centraila",
                "time_traveled": 1.2,
                "distance_traveled": 45.5,
                "cost": 23.00,
                "path":[r1,r4,r5,r6]
            }
        }]
},
"network":{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "LineString",
                "coordinates": [[-122,46.5],[..],[..],[...][-123,46.72]]
            },
            "properties": {
                "id":"r1",
                "distance": 1.2,
                "time": 45.5,
                "cost": 23.00,
                "capacity":40,
                "connections":[[r0,r3],[r2,r5]],
                "paths":["farm1-centrailia","BRFISYB"]          
            }
        }]
}
```

This allows a client to add new paths incrementally.  The id's for the paths and network will be constant from one call to the next.

**Comment by jrmerz** [comment]
1. Why is the word 'file' in here?  Do you mean request and response format?

_Updated description to eliminate file_
1. I think we should try and limit the request payload size as much as possible (for that matter the response too).  Supplying params as: sources={id: [lat,lng]}, destination=lat/lng, and options={}, we can save a lot of network bandwidth.

_Don't see a huge savings on the inputs for that, esp. w.r.t using the GeometryCollection as decided above. I guess I do see a savings in output, but then I'm less excited about not using geojson for that complex response.  Protocol Buffers :)_
1. ID's.  Aren't the source lat,lng a unique id?

_Using the GeometryCollection, they would be.  I prefer the put those through the MD5 blender, just so they match paths as well.  I threw in the FeatureCollection, predominantly so a client wouldn't have to check that no points had matching coordinates.  I would assume we'd use the GeometryCollection method, so I don't mind starting with that._
1. Agree with with sending response network as single geojson FeatureCollection object.  And like using id, based strategy path lookup. As for the individual routes, can't these just be expressed by the properties object in your 'path' collection above?

_The current proposal has two FeatureCollections.  Both are reasonable. I assumed options could include, `paths=false; network=true`,  which is way i made them separate.  The reason to not put the route in the 'paths' column is for a few reasons._  
1. You can compute capacities and densities by adding up the individual paths traveled by walking the path array in the paths response.
2. This works with incremental calls to the service, as the path identifiers don't change, so you can get 
3. You don't have to traverse the path to accomplish that.
4. You can actually have a more featureful client, for example updating costs with changes to the fuel or labor, since you know how to cost each component.

Follow ups.  What datasets and software are you looking to use to create this service?

**Comment by qjhart** [comment]
Comments updated above.

For the datasets, I plan to use the  [BTS transportation atlas](https://www.rita.dot.gov/bts/sites/rita.dot.gov.bts/files/publications/national_transportation_atlas_database/2015/liner).  Specifically, the  Freight Analysis Framework FAF data.

For software, pgrouting, part of postgresql.  Previously I did this by adding extra nodes to that routing table, don't think we want to do that this time around.
